part of 'theme.dart';

const int PWR_BTN_ICON_COLOR_INACTIVE = 0;
const int PWR_BTN_ICON_BGR_COLOR_INACTIVE = 1;
const int PWR_BTN_BGR_COLOR_INACTIVE = 2;
const int APPBAR_BGR_COLOR_INACTIVE = 3;
const int APPBAR_ICON_COLOR_INACTIVE = 4;

const int PWR_BTN_ICON_COLOR_ACTIVE = 5;
const int PWR_BTN_ICON_BGR_COLOR_ACTIVE = 6;
const int PWR_BTN_BGR_COLOR_ACTIVE = 7;
const int APPBAR_BGR_COLOR_ACTIVE = 8;
const int APPBAR_ICON_COLOR_ACTIVE = 9;

const int TOOLTIP_COLOR = 10;

const int SETTINGS_DELIMITER_COLOR = 11;
const int CONFIG_BACKGROUND_COLOR = 12;
const int PRIMARY_COLOR = 13;
const int TOOLTIP_ALERT_COLOR = 14;

const int SERVER_LOCATIONS_COUNT_COLOR = 15;
const int LINK_COLOR = 16;
const int INTRO_DESCRIPTION_COLOR = 17;
const int SELECT_PLAN_BACKGROUND = 18;
const int SELECT_PLAN_TOGGLE_BACKGROUND = 19;
const int SELECT_PLAN_DIVIDER_COLOR = 20;

const int LOCATIONS_LIST_DIVIDER_COLOR = 21;
const int LOCATIONS_LIST_CATEGORY_BACKGROUND_COLOR = 22;
const int LOCATIONS_LIST_ITEM_BACKGROUND_COLOR = 23;

class CustomThemeColors {
  final Map<int, Color> _colors;

  CustomThemeColors(this._colors);

  Color getColor(int key) => _colors[key];
}

final CustomThemeColors darkAppThemeColors = _buildDarkCustomThemeColors();
final CustomThemeColors lightAppThemeColors = _buildLightCustomThemeColors();

CustomThemeColors _buildLightCustomThemeColors() {
  return CustomThemeColors(<int, Color>{
    PWR_BTN_ICON_COLOR_INACTIVE: Color(0xFFFFFFFF),
    PWR_BTN_ICON_BGR_COLOR_INACTIVE: Color(0xFF5B5863),
    PWR_BTN_BGR_COLOR_INACTIVE: Color(0xFFFFFFFF),
    APPBAR_BGR_COLOR_INACTIVE: Color(0xFFF5F3ED),
    APPBAR_ICON_COLOR_INACTIVE: Color(0xFF5B5863),

    PWR_BTN_ICON_COLOR_ACTIVE: Color(0xFFFFFFFF),
    PWR_BTN_ICON_BGR_COLOR_ACTIVE: Color(0xFF62D5B4),
    PWR_BTN_BGR_COLOR_ACTIVE: Color(0xFFFFFFFF),
    APPBAR_BGR_COLOR_ACTIVE: Color(0xFF62D5B4),
    APPBAR_ICON_COLOR_ACTIVE: Color(0xFFFFFFFF),

    TOOLTIP_COLOR: Color(0xFFFFFFFF),
    TOOLTIP_ALERT_COLOR: Color(0xFFFD3E72),

    SETTINGS_DELIMITER_COLOR: Color(0xFFEDEBE5),
    CONFIG_BACKGROUND_COLOR: Color(0xFFFAE6E7),
    PRIMARY_COLOR: Color(0xFFFD3E72),

    SERVER_LOCATIONS_COUNT_COLOR: Color(0xFF8F8D91),
    LINK_COLOR: Color(0xFF8F8D91),
    INTRO_DESCRIPTION_COLOR: Color(0xFF8F8D91),
    SELECT_PLAN_BACKGROUND: Color(0xFFFFFFFF),
    SELECT_PLAN_TOGGLE_BACKGROUND: Color(0xFFFFFFFF),
    SELECT_PLAN_DIVIDER_COLOR: Color(0xFFEDEBE5),


    LOCATIONS_LIST_DIVIDER_COLOR: Color(0xFFEDEBE5),
    LOCATIONS_LIST_CATEGORY_BACKGROUND_COLOR: Color(0xFFF9F8F4),
    LOCATIONS_LIST_ITEM_BACKGROUND_COLOR: Color(0xFFFFFFFF),

  });
}

CustomThemeColors _buildDarkCustomThemeColors() {
  return CustomThemeColors(<int, Color>{
    PWR_BTN_ICON_COLOR_INACTIVE: Color(0xFF585661),
    PWR_BTN_ICON_BGR_COLOR_INACTIVE: Color(0xFFD6D5D2),
    PWR_BTN_BGR_COLOR_INACTIVE: Color(0xFF333138),
    APPBAR_BGR_COLOR_INACTIVE: Color(0xFF36343B),
    APPBAR_ICON_COLOR_INACTIVE: Color(0xFFC7C5C4),

    PWR_BTN_ICON_COLOR_ACTIVE: Color(0xFFFFFFFF),
    PWR_BTN_ICON_BGR_COLOR_ACTIVE: Color(0xFF62D5B4),
    PWR_BTN_BGR_COLOR_ACTIVE: Color(0xFF3F3D45),
    APPBAR_BGR_COLOR_ACTIVE: Color(0xFF62D5B4),
    APPBAR_ICON_COLOR_ACTIVE: Color(0xFFFFFFFF),

    TOOLTIP_COLOR: Color(0xFF2C2B30),
    TOOLTIP_ALERT_COLOR: Color(0xFFFD3E72),

    SETTINGS_DELIMITER_COLOR: Color(0xFF312F36),
    CONFIG_BACKGROUND_COLOR: Color(0xFF333138),
    PRIMARY_COLOR: Color(0xFFFD3E72),

    SERVER_LOCATIONS_COUNT_COLOR: Color(0xFFC7C5C4),
    LINK_COLOR: Color(0xFFACA9B0),
    INTRO_DESCRIPTION_COLOR: Color(0xFFC7C5C4),
    SELECT_PLAN_BACKGROUND: Color(0xFF36343B),
    SELECT_PLAN_TOGGLE_BACKGROUND: Color(0xFF2A282E),
    SELECT_PLAN_DIVIDER_COLOR: Color(0xFF2F2D33),

    LOCATIONS_LIST_DIVIDER_COLOR: Color(0xFF312F36),
    LOCATIONS_LIST_CATEGORY_BACKGROUND_COLOR: Color(0xFF36343B),
    LOCATIONS_LIST_ITEM_BACKGROUND_COLOR: Color(0xFF3F3D45),

  });
}
