/// Flutter icons WeVpnIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeVpnIcons
///      fonts:
///       - asset: fonts/WeVpnIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class WeVpnIcons {
  WeVpnIcons._();

  static const _kFontFam = 'WeVpnIcons';

  static const IconData power_settings_new = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData time_clock = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData a_back = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData w_play = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData a_up = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData a_down = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData w_no_logs = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData w_incognito = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData w_devices = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData bucket = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData c_remove = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_right = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData a_expanded = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData a_collapsed = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData power_swtich = const IconData(0xe83e, fontFamily: _kFontFam);
}
